language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: zucchini
  password:
    secure: m2s3eGn006osjOg6esHHyezZDq1jN4ACjrEwSCOa7X8pYU8tPvK7KyLo4P/uGMxJ40krxUsfYojfKpqyR0aV93o3JR47vVqe+F+c1wnYEqdMZBQWTa+l+mP3votXT88qdX0vPTyWKocWWAjkkdO5CFuZIoLeEJeqlRed1kfUWVtQLyKsrv/oAPDu+tTxf659wxG1nZykt/EcUOkFI9NsG2tOqsTYrEi9Rkr3oHxVCZll38wIhsVm3WQna27yz2z4t9jzjxEHdDIH4fZmfaZGNAzZKPsNjLabJHD0dNS/kj5/gKaaOcmCejNfbpTBYfk93q5LyG2d0Uu6X1KFqKwBHkARt0o/Xg8jWyYbO8cIB/B71YroAwFNWTt8vxrASu8XYKlOivLSoFtJjTZ9GyHt4qBsGNPOB5tvlS7Oy21b2tRb9dj+HaRLoOuGAJFvrSAeCd08yJbQuwi+1jrMB2LBWCFUu+tBO49ul2JosE+95IE+tdmk6bS51GRFdgJZVA0P7pteCr3qB8zjWKAdcgyl831sRZrYgb1BebYddZ/uJaCAJejHgyEY3nDDIqfC5ncAHnxnIj0r5yAxVrERoiRDfYFDfjvwjfQ0Kz3/wS58b0JAlB4GpRm5XN2r+BA0ppnoQ2rgrjMNfUL1YlSJMCwyXXLw8yW4J6skovPAsgveGIc=
  on:
    tags: true
    repo: zucchini/appel
    python: 3.6
